#!/usr/bin/env bash

#Concatenates all of the trees generated by phyloFit in a large file, indexed by the sequence name.

DIR="/Xnfs/lbmcdb/Semon_team/jcaron"
MODDIR="/Xnfs/lbmcdb/Semon_team/jcaron/modfiles"
OUTDIR="/Xnfs/lbmcdb/Semon_team/jcaron/trees"
mkdir -p "$OUTDIR"

#Main command
for mod in "$MODDIR"/*.mod; do
    base=$(basename "${mod%.mod}")
    newick=$(grep "^TREE:" "$mod" | sed 's/^TREE: //')
    printf '%s\t%s\n' "$base" "$newick"
done > "$OUTDIR"/tree.txt
